### ISSUE TITLE
Complete template example

### ISSUE THREAD

**Issue by mikeq** [react-d3-library/react-d3-library#55]
Do you have a complete example using the template charts, I can't seem to get anything displaying and there are no errors in the console.

Is there something else I'm supposed to be including? It is not clear from the template documentation if so.

```
import React from 'react';
import rd3 from 'react-d3-library';
const LineChart = rd3.LineChart;

class DGraph extends React.Component {
  render() {
    const dataObj = {};
    dataObj.dataset = [
      {time: '24-Apr-07', value: 93.24},
      {time: '25-Apr-07', value: 95.35 },
      {time: '26-Apr-07', value: 98.84 },
      {time: '27-Apr-07', value: 99.92 },
      {time: '28-Apr-07', value: 99.80 }
    ];
    dataObj.height = 350;
    dataObj.width = 750;
    dataObj.margins = {top: 20, right: 10, bottom: 0, left: 10};

    return (
      <div>
        <h1>D3 Graph</h1>
        <LineChart data={dataObj}/>
      </div>
    );
  }
}

export default DGraph;
```

- "react": "^15.4.2"
- "react-d3-library": "^1.1.7"
- "d3": "3.5.17"

**Comment by danieljoonlee** [comment]
hey mike, i've been recently thinking about removing template charts recently actually because it bloats the library, and in most cases you will import D3, so having two copies of D3 might not be ideal.  your best bet would be to implement the chart you want with d3 and use the library to implement it in react.

**Comment by mikeq** [comment]
Ah cool.  Thanks for the quick reply.
